name = "Improved Survival"
author = "Pyrotonic"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e030e28b16867069dfdac60d7fb4fa906b82644343b621896507c6aceb4cb45"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
